### PR TITLE
Added 64-bit text & line break, separating version # and size

### PR DESCRIPTION
**Pull request by ejerez**
Issue #2183 

### Changes Summary

-  Added '64 bit' text next to download size
-  Added a line break

This pull request [ is ] ready for review.

*Note: First pull request :) Thank you Elementary team for delivering an amazing OS!

### CODE REVIEW

**Comment by lewisgoddard** [comment]
@btkostner Should we be excluding `package-lock.json`?

**Comment by btkostner** [comment]
@lewisgoddard The `package-lock.json` file should be excluded unless you want to update dependencies (which we do not in this PR).

**Comment by ejerez** [comment]
> Styles look good. Just need to remove the `package-lock.json`

@btkostner I believe I have removed the package-lock.json file now. Please verify. Thank you.

**Comment by btkostner** [comment]
@ejerez the PR now removes the `package-lock.json` from the repo. You should just remove the `package-lock.json` from the PR.

Try doing:
```sh
git checkout origin/master -- package-lock.json
```

**Comment by btkostner** [comment]
@ejerez You forgot to `git commit` and `git push`. I fixed it. Thank you for the contribution!

**Pull request merged**
