### PR TITLE
Update press logos on mouse hover and click

### PR DESCRIPTION
**Pull request by user501254**
Fixes https://github.com/elementary/website/pull/431

### Changes Summary

- increase opacity of press logos when hovering over them
- move the press logos slightly into the page on click

~This is how it looks:~
gif-3-b6d8dc5ce0

This pull request is ready for review.

### CODE REVIEW

**Comment by lewisgoddard** [comment]
If we add this we'd probably want a CSS transition.

**Comment by danrabbit** [comment]
I dig it. I agree I'd like a simple `ease-in-out`

**Comment by user501254** [comment]
@lewisgoddard @danrabbit 
I have made a new commit to add the `ease-in-out` transition with a duration of 250ms, keeping it consistent with rest of the transitions on the page..

**Comment by user501254** [comment]
We could probably also use the same transition affect on `.oss-logo` in [Open Source ⋅ elementary](https://elementary.io/open-source) towards the bottom of the page. The opacity change looks quite abrupt.

**Comment by lewisgoddard** [comment]
That seems like a good idea.

**Pull request merged**
