### PR TITLE
Automate updates of Submodules

### PR DESCRIPTION
**Pull request by lewisgoddard**
This pull request is ready for review.

### CODE REVIEW

**Comment by btkostner** [comment]
For these, we should just put them all in a single `update.yaml` file with a single cron job. It will clean up the actions tab in GitHub because there will only be one thing instead of an `update submodules` and `update translations` etc.

**Comment by lewisgoddard** [comment]
@btkostner That seems far more likely to break, a single error would halt the whole process.

**Comment by btkostner** [comment]
@lewisgoddard no it wouldn't. It only stops things that depend on it. If we had translations and submodules on the same pipeline, they would run at the same time.

**Comment by lewisgoddard** [comment]
That still seems like an uncomfortable mix of disciplines.

**Pull request closed without merging**
