### PR TITLE
Redirect HIG

### LINKED ISSUE #2677: Redirect HIG to new HIG
We have ported the HIG to GitBook alongside our other docs, and started making large improvements. There are a few regressions, but we should probably still redirect the old HIG from here to the new one because all the effort is being put in there.

https://docs.elementary.io/hig/

We should also transfer all HIG issues from this repo to [elementary/hig](https://github.com/elementary/hig).

### PR DESCRIPTION
**Pull request by cassidyjames**
Fixes #2677. We've been updating content there that hasn't been backported, so it's time to switch over.

### CODE REVIEW

**Comment by danrabbit** [comment]
There are some large outstanding issues that need to be resolved first

**Comment by danrabbit** [comment]
for example https://github.com/elementary/hig/issues/7 and https://github.com/elementary/hig/issues/9

**Review by danrabbit — APPROVED** [review]
:rocket:

**Comment by dar5hak** [comment]
The _Design_ card on https://developer.elementary.io/ still takes to the old link, which does not redirect.

```html
<a class="card" href="https://elementary.io/docs/human-interface-guidelines">…</a>
```

**Pull request merged**
