### PR TITLE
Removes gulp rename package.

### LINKED ISSUE #2093: Browser caching on Chrome breaks website
Looks like Chrome is caching the CSS/JS and it is not being updated when the website is updated. I would recommend cache fingerprinting  (use `main.0fklh924sd834.css` instead of `main.css`).

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/65035183-browser-caching-on-chrome-breaks-website?utm_campaign=plugin&utm_content=tracker%2F10548672&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F10548672&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by RMcNeely**
Fixes #2093 
 
### Changes Summary

- Uses base option of rev.manifest function instead of gulp-rename 
- Removes gulp-rename dependency

This pull request is ready for review.

### CODE REVIEW

**Comment by RMcNeely** [comment]
@davidmhewitt just make sure I didn't mess anything up late last night while I was working on this. We can get this merged into your branch and then I can approve yours.

**Comment by davidmhewitt** [comment]
The content of `manifest.json` with my branch:
```
{
  "styles/blog.css": "styles/blog-4e82dc813d.css",
  "styles/brand.css": "styles/brand-358596af81.css",
  "styles/capnet-assist.css": "styles/capnet-assist-af26da4786.css",
  "styles/developer.css": "styles/developer-fdcf2f8298.css",
  "styles/docs.css": "styles/docs-a387541f9e.css",
  "styles/get-involved.css": "styles/get-involved-91ad6d4d9b.css",
  "styles/home.css": "styles/home-23f27addf3.css",
  "styles/main.css": "styles/main-2c1d41872c.css",
  "styles/oem.css": "styles/oem-39ed731458.css",
  "styles/open-source.css": "styles/open-source-e6f458e8d2.css",
  "styles/press.css": "styles/press-fb4619e5fc.css",
  "styles/privacy.css": "styles/privacy-b13b20974b.css",
  "styles/solarized_dark.css": "styles/solarized_dark-aac62bf22d.css",
  "styles/solarized_dark_bash.css": "styles/solarized_dark_bash-90daa02a49.css",
  "styles/solarized_light.css": "styles/solarized_light-d4ebf1f32b.css",
  "styles/support.css": "styles/support-4fcac4e250.css",
  "styles/team.css": "styles/team-d44e6921ee.css"
}
```

The content of `manifest.json` with this branch:
```
{
  "blog.css": "blog-4e82dc813d.css",
  "brand.css": "brand-358596af81.css",
  "capnet-assist.css": "capnet-assist-af26da4786.css",
  "developer.css": "developer-fdcf2f8298.css",
  "docs.css": "docs-a387541f9e.css",
  "get-involved.css": "get-involved-91ad6d4d9b.css",
  "home.css": "home-23f27addf3.css",
  "main.css": "main-2c1d41872c.css",
  "oem.css": "oem-39ed731458.css",
  "open-source.css": "open-source-e6f458e8d2.css",
  "press.css": "press-fb4619e5fc.css",
  "privacy.css": "privacy-b13b20974b.css",
  "solarized_dark.css": "solarized_dark-aac62bf22d.css",
  "solarized_dark_bash.css": "solarized_dark_bash-90daa02a49.css",
  "solarized_light.css": "solarized_light-d4ebf1f32b.css",
  "support.css": "support-4fcac4e250.css",
  "team.css": "team-d44e6921ee.css"
}
```

This is the issue I was having with `rev`. I don't know if it's buggy, or if there's something I don't understand.

**Comment by RMcNeely** [comment]
good catch. let me see if I can fix that. This is why its a separate PR

**Comment by davidmhewitt** [comment]
@RMcNeely Did you have chance to look at this any further? I feel like it would be good to get cache busting merged in prior to the release of the next version of the OS so we don't have issues with cached pages after the release.

**Comment by RMcNeely** [comment]
I took a peek at the source code for Gulp rev and it's just too strict to allow what I was looking to do. Let's just close this PR and approve the other one.

**Pull request closed without merging**
