### PR TITLE
Improve German Translation

### PR DESCRIPTION
**Pull request by crydotsnake**
Everywhere I dared, i try to improve the German Translation. Some times, i wasnt really sure how to translated the words.. But if you wish, i can continue that!.

### CODE REVIEW

**Comment by tintou** [comment]
Hi there, the website is translated in German here https://l10n.elementary.io/projects/website/index/de/ feel free to create an account and contribute :slightly_smiling_face: Thanks!

**Comment by crydotsnake** [comment]
Hi @tintou, didnt know that.. so i can close the PR?.

**Comment by tintou** [comment]
@crydotsnake no worries, but yes, please use the translation platform

**Comment by crydotsnake** [comment]
Hm.......

**Pull request closed without merging**
