### PR TITLE
Add toast for Tuesday

### PR DESCRIPTION
**Pull request by cassidyjames**
Screenshot from 2021-08-04 16-37-01

### CODE REVIEW

**Comment by btkostner** [comment]
Worth remembering that this causes hundreds of browsers to refresh our homepage at the same time, basically DDOSing ourselves, sooooooo we should probably have #web on standby in case stuff crashes.

**Comment by danrabbit** [comment]
I guess if we're not using the countdown anymore we can dump all its styles and JS and whatever else it uses?

**Comment by cassidyjames** [comment]
@danrabbit yeah will do.

**Review by danrabbit — APPROVED** [review]
L E T S   G O :shipit:

**Pull request merged**
