### PR TITLE
Add liberapay to funding

### LINKED ISSUE #2227: Add Liberapay to funding section
Someone mentioned it's not easy to find.

### PR DESCRIPTION
**Pull request by silksow**
Fixes #2227 

### Changes Summary

Add Liberapay logo svg to images/get-involved
Add Liberapay to funding section in get-involved.php

This pull request is ready for review.

### CODE REVIEW

**Comment by lewisgoddard** [comment]
image

**Comment by cassidyjames** [comment]
I think I'd rather switch Patreon and Bountysource to be 50/50 at the top, and then have PayPal, Liberapay, and the store as thirds below. My thinking is that Patreon and Boundysource are more significant ways folks can set up recurring contributions, whereas Liberapay is less-used and less well-known.

**Comment by lewisgoddard** [comment]
image

**Comment by cassidyjames** [comment]
Made some tweaks for the layout, but it's good to go now. Thanks!

image

**Pull request merged**
