### PR TITLE
Update Font Awesome Pro to version 5.9.0

### LINKED ISSUE #2151: Update Slack Icon
Slack just reviewed their interface and icon as explained in this article : https://slackhq.com/say-hello-new-logo
Maybe the old icon should be replaced by the new one ?

### PR DESCRIPTION
**Pull request by lewisgoddard**
Fixes #2151

This pull request is ready for review.

### CODE REVIEW

**Comment by lewisgoddard** [comment]
openssl dgst -sha384 -binary all.css | openssl base64 -A
    PzE/Pz8/I3c/P3ZiPws/P0gGKj8/P38/Pz9PPy56Oj8/Pyo7Pz8/JWRWP3NhPz8vDQo=

**Comment by NathanBnm** [comment]
Is the integrity key correct? Maybe it's still the same issue.

**Comment by NathanBnm** [comment]
@btkostner @lewisgoddard apparently FontAwesome reviewed their way to import fonts. Now you have to include an script with their new icon kit system. Just check on their website for further info. This will permit to manage your icons directly from your account and always have the last version.

I've just used it for a personal project and it's working fine. You just have to add a script like that:

`<script src="https://kit.fontawesome.com/<number>.js"></script>`

Then you'll have your FontAwesome kit loaded.

**Comment by lewisgoddard** [comment]
Okay, we 100% need access to the account with the Pro subscription. They now use a link that is unique and carries settings within it.

**Comment by btkostner** [comment]
Looks like the migration path to the new JS kit way would require us to make a list of all the icons we use on the site and probably change the way we use them. I think we should do this as a stop gap first.

**Pull request merged**
