### PR TITLE
Fix #1442 & #1345 - Update npm on Vagrantfile and remove node_modules…

### LINKED ISSUE #1442: Run website in vagrant
I try to mount the website in vagrant but after to run vagrant up and enter localhost:8000 in the browser the website not load the styles and script.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/38573777-run-website-in-vagrant?utm_campaign=plugin&utm_content=tracker%2F10548672&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F10548672&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by sergiouve**
### Fix #1442 & #1345 - Update npm on Vagrantfile and remove node_modules symbolic link

This should fix the Vagrant box.
There was a problem with the npm version which caused some packages to not be installed correctly which caused webpack to not be configured correctly which resulted in the assets not being built...

So I added a npm update in the Vagrantfile right after the installation of Node and removed the node_modules symbolic link as it was also causing troubles with npm.

### CODE REVIEW

**Comment by btkostner** [comment]
@sergiouve did you test this on Windows or on Linux?

**Comment by sergiouve** [comment]
@btkostner I tested it in my Fedora machine, everything runs smoothly... I booted up my Windows laptop (Windows 8), set everything up and... nope, **it doesn't work in Windows**, there's still the same issue with webpack and the assets builds... I'll look closer into it tomorrow.

**Comment by btkostner** [comment]
@sergiouve Awesome! Thank you for testing this on Windows. Sadly I don't really have a developer install of Windows to test and assist you on this.

**Comment by lewisgoddard** [comment]
I'm going to leave this for @btkostner to approve or close.

**Pull request closed without merging**
