### PR TITLE
Automatic blog posts on homepage

### PR DESCRIPTION
**Pull request by lewisgoddard**
### Changes Summary

- [x] Loads most recent blog posts and replaces `#whats-new`
- [x] Styling
- [x] Date formatting
- [x] Keep the "What's new" header?

This pull request is ready for review at https://beta.elementary.io/automatic-blog/

### CODE REVIEW

**Comment by lewisgoddard** [comment]
image

**Comment by lewisgoddard** [comment]
image

**Comment by lewisgoddard** [comment]
These styles are just pulled from blog-template, which doesn't do that. I don't think that's really necessary for this pull request.

**Comment by btkostner** [comment]
Alright. I'll move that request there then.

**Comment by lewisgoddard** [comment]
@cassidyjames Seems like the reference on the blog API was wrong, so was always falling back. Should start working soon, or right away at the new endpoint in testing.

**Comment by lewisgoddard** [comment]
@cassidyjames Do we want to pull from [all posts](https://blog.elementary.io/feed.json) or [updates](https://blog.elementary.io/feed/updates.json)? It is a simple string change.

**Comment by cassidyjames** [comment]
@lewisgoddard `updates`, please. :)

**Comment by cassidyjames** [comment]
This looks really close! Only major issue I see now is styling on smaller displays.

Screenshot from 2019-10-24 17 31 30@2x

**Comment by lewisgoddard** [comment]
@cassidyjames Should be responsive in the same way as the blog now.

**Pull request merged**
