### PR TITLE
Increase download timeout (again)

### PR DESCRIPTION
**Pull request by danrabbit**
It seems like we're still having customers that are having trouble with this redirect race condition business. Increase the timeout even more to try to avoid this

### CODE REVIEW

**Comment by btkostner** [comment]
At this point I think we should just omit it until we can get a better fix.

**Comment by cassidyjames** [comment]
Yeah, moving the download logic to the thank-you page makes sense to me if we can do that as a permanent fix.

**Comment by danrabbit** [comment]
@btkostner Yeah I kinda feel like maybe we should just kill the redirect for now

**Comment by btkostner** [comment]
Same

**Pull request closed without merging**
