### PR TITLE
Fix Webseed URI Encoding

### LINKED ISSUE #2448: URI Encode Webseed in Magnet
The magnet URL that is currently on the homepage is a mix of URI encoding and non-URI encoding, in the webseed url (at the end):

```
magnet:?xt=urn:btih:aeabff64ed6d2ab735cca7d0e7443669d578b7b7&dn=elementaryos-5.1-stable.20200603.iso&tr=https%3A%2F%2Fashrise.com%3A443%2Fphoenix%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.ccc.de%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.publicbt.com%3A80%2Fannounce&ws=http://nyc3.dl.elementary.io/download/{{timeinbase64}}/elementaryos-5.1-stable.20200603.iso
```

Some magnet parsers have trouble with this, such as [webtorrent/parse-torrent](https://github.com/webtorrent/parse-torrent).

1. Try to add the magnet url from the Elementary homepage to a Webtorrent site such as [instant.io](https://instant.io).
2. Inspect the torrent client in the console and note that a webseed wasn't added

This should be corrected to either be entirely not URI encoded:

```
magnet:?xt=urn:btih:aeabff64ed6d2ab735cca7d0e7443669d578b7b7&dn=elementaryos-5.1-stable.20200603.iso&tr=https://ashrise.com:443/phoenix/announce&tr=udp://open.demonii.com:1337/announce&tr=udp://tracker.ccc.de:80/announce&tr=udp://tracker.openbittorrent.com:80/announce&tr=udp://tracker.publicbt.com:80/announce&ws=http://nyc3.dl.elementary.io/download/{{timeinbase64}}/elementaryos-5.1-stable.20200603.iso
```

or entirely URI encoded:

```
magnet%3A%3Fxt%3Durn%3Abtih%3Aaeabff64ed6d2ab735cca7d0e7443669d578b7b7%26dn%3Delementaryos-5.1-stable.20200603.iso%26tr%3Dhttps%3A%2F%2Fashrise.com%3A443%2Fphoenix%2Fannounce%26tr%3Dudp%3A%2F%2Fopen.demonii.com%3A1337%2Fannounce%26tr%3Dudp%3A%2F%2Ftracker.ccc.de%3A80%2Fannounce%26tr%3Dudp%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce%26tr%3Dudp%3A%2F%2Ftracker.publicbt.com%3A80%2Fannounce%26ws%3Dhttp%3A%2F%2Fnyc3.dl.elementary.io%2Fdownload%2F{{timeinbase64}}%2Felementaryos-5.1-stable.20200603.iso
```

### PR DESCRIPTION
**Pull request by leoherzog**
Fixes #2448 

### Changes Summary

- Encoded the Webseed URL to match the rest of the magnet

This pull request is ready for review.

### CODE REVIEW

**Comment by leoherzog** [comment]
@btkostner Hey, looks like `%26ws%3D` should actually be `&ws=` if it's supposed to match the other tracker URLs... `parse-torrent` and others still have trouble with this format. I've updated [my fork](https://github.com/leoherzog/website). Would you like to re-open this pull request, or do you want me to start a new one? Or do you just want to make that edit yourself? 😆

**Comment by lewisgoddard** [comment]
@leoherzog Can you open this pull request, or a new one? I can't approve it if I open it.

**Comment by leoherzog** [comment]
@lewisgoddard I don't seem to have a "reopen" button now that it's merged...

**Comment by lewisgoddard** [comment]
@leoherzog Can you open a new one on the same branch?

**Comment by leoherzog** [comment]
Opened https://github.com/elementary/website/pull/2451

**Pull request merged**
