### PR TITLE
Juno

### PR DESCRIPTION
**Pull request by cassidyjames**
Based on #1944 with a bit of a reduced diff, plus changes for Juno.

### Home

- Refreshed AppCenter section
  - White-on-purple
  - New copy
  - Switched from links to buttons
- Sections moved around a bit
- Added "privacy-respecting" to tagline
- Added "Fast" section to three small feature callouts
- Moved "Privacy" section to its own big beautiful spot toward the bottom
  - Tattletale section
  - Location services section
  - Housekeeping section
- Refreshed apps section
  - Wallpaper/gradient background
  - New screenshots
  - Tweaked copy
- New Parental Controls section
- New Keyboard Shortcuts section

### Press page

- Replaced "Press Kit" section with "Brand Resources"
- New Juno section with links to press kit and announcement

## Screenshot

website-screenshot

## Todo

- [x] Update hero screenshot for Juno 
- [x] Fix Shortcut Overlay squishing https://github.com/elementary/website/pull/2057#issuecomment-426031104
- [ ] Tweak Parental Controls title wrapping https://github.com/elementary/website/pull/2057#issuecomment-426022860
- [ ] Update Parental Control screenshot with HiDPI avatar fix
- [x] Update copy on Press page
- [ ] Update ISO details for Juno
- [x] Update press kit link on Press page
- [x] Update Announcement link on home page
- [x] Update Announcement link on press page
- [ ] Wait for Juno to actually be released :wink:

### CODE REVIEW

**Comment by danrabbit** [comment]
At mobile sizes, the title for the parental controls section wraps oddly

screenshot from 2018-10-01 11 54 23 2x

This is how we handle that in the apps sections

screenshot from 2018-10-01 11 54 44 2x

Not sure if it would be better to just indent since that does save vertical space for labels with no wrap? But either way we should be consistent

**Comment by cassidyjames** [comment]
Need to update the Parental Control screenshot with the HiDPI fix.

**Comment by jwinnie** [comment]
Suggestion: The "BETA" badge on [developer.elementary.io](https://developer.elementary.io) should probably be removed, since AppCenter is really no longer in beta. I'm not sure whether it's in elementary/houston or elementary/website...I can make a PR if I can find it.

**Comment by cassidyjames** [comment]
@jwinnie it's in Houston

**Comment by jwinnie** [comment]
Where? https://github.com/elementary/houston/search?utf8=%E2%9C%93&q=publish+on+appcenter&type=

**Comment by cassidyjames** [comment]
Hm, I'm not sure in the v2 branch. In master, it's at https://github.com/elementary/houston/blob/master/src/houston/views/index.pug

**Comment by jwinnie** [comment]
Thank you very much! Pulled https://github.com/elementary/houston/pull/662
Also, feedback on the buttons: IMO the contrast is too low on hover. Maybe the buttons should get darker and not lighter on hover. The apps page is also broken (cut off at the bottom) when zoomed in 150% or more.

**Comment by megatux** [comment]
There are still a lot of references to "Scratch" editor in the translations. e.g. https://github.com/elementary/website/blob/juno/_lang/es/index.json#L29

**Comment by cassidyjames** [comment]
@megatux this has not been merged yet, so translations are not being written against it.

**Pull request merged**
