### PR TITLE
Removed shorthand tags and replaced them with <?php as per the guidelines

### PR DESCRIPTION
**Pull request by javielico**
As per issue #1778

### Changes Summary
- Changed the shorthand tags on brand.php for the long ones

### CODE REVIEW

**Comment by javielico** [comment]
Hi @btkostner do you mean that the line should be: 
images/brand/logotype.png" alt="elementary Logotype"/>

**Comment by btkostner** [comment]
Yep

**Comment by javielico** [comment]
That's now done for you 👍

**Comment by btkostner** [comment]
Awesome. Thank you for the PR!

**Pull request merged**
