### PR TITLE
change continue button margin to padding

### LINKED ISSUE #1315: Flipclock Continue Button difficult to push on iOS
On Apple’s mobile Safari the continue button is hard to push, because it renders to the bottom of the page.

Problem: if you tap in this area Safari‘s UI fades in again.. But due to the flipclock refreshing the complete overlay again, the button appears on the bottom again, if you scroll it up a little bit.

Solution: Add a few pixels of space under the Continue-Button.

### PR DESCRIPTION
**Pull request by btkostner**
Fixes #1315

I need to get confirmation that this does not cause double scroll bar when it shouldn't.

### CODE REVIEW

**Comment by lewisgoddard** [comment]
@bigfatbird If we deploy this to a test page, are you capable of testing the change?
@btkostner Can you deploy this to the beta domain?

**Comment by bigfatbird** [comment]
Sure, I do have an iPhone 6s.

Von meinem iPhone gesendet

**Comment by btkostner** [comment]
I'm currently in transit, so the beta site will not be up for another 7 or so hours. Sorry about the delay

**Comment by btkostner** [comment]
Here it is @bigfatbird, let us know if this is better for you.

https://beta.elementary.io/branch/origin/countdown-domain/countdown

**Comment by bigfatbird** [comment]
It’s perfect. :)

**Comment by btkostner** [comment]
awesome, thank you!

**Pull request merged**
