### PR TITLE
Adds chunk hashing for cache busting to Webpack

### LINKED ISSUE #2093: Browser caching on Chrome breaks website
Looks like Chrome is caching the CSS/JS and it is not being updated when the website is updated. I would recommend cache fingerprinting  (use `main.0fklh924sd834.css` instead of `main.css`).

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/65035183-browser-caching-on-chrome-breaks-website?utm_campaign=plugin&utm_content=tracker%2F10548672&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F10548672&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by RMcNeely**
Fixes #2093 

### Changes Summary

- Adds cache busting for JS built in Webpack
- Adds cache busting for CSS via adding a time string to CSS files
- Updates Webpack to v4
  - Uses Terser Webpack Plugin as new default method for minification

This pull request [ is ] ready for review.

### CODE REVIEW

**Comment by btkostner** [comment]
We need a manifest generated and a bit of PHP to lookup the file names in that manifest

**Comment by RMcNeely** [comment]
Added a manifest file for both the JS and CSS parts. Unfortunately I can't seem to figure out how to chunk common the same way that it was being before upgrading Webpack, so jQuery is getting loaded multiple times.

**Comment by RMcNeely** [comment]
If I recall correctly I think some other chunk was pulling in jQuery as well? I'll pull again and take a look at it.

**Comment by RMcNeely** [comment]
Still never got a chance to check out the jQuery issue but I did resolve conflicts and bump some dependencies.

**Comment by RMcNeely** [comment]
Closed as stale

**Pull request closed without merging**
