### PR TITLE
Update country.json

### PR DESCRIPTION
**Pull request by jefersonpassos**
Fixes #

### Changes Summary

- 
- 
- 

This pull request [ is / is not ] ready for review.

### CODE REVIEW

**Comment by larouxn** [comment]
Will this PR be good to go once the `_lang/pt_BR/docs/installation.json` changes are reverted?

**Comment by lewisgoddard** [comment]
I believe so, yes.

**Comment by larouxn** [comment]
👍  @jefersonpassos, can I revert those translation file changes so we can get this merged?

**Comment by jefersonpassos** [comment]
Yes.

Em 6 de jan de 2018 23:28, "Nicholas La Roux" <notifications@github.com>
escreveu:

**Comment by gamerlv** [comment]
As all relevant changes have been merged via PR #1870 I am closing this one.

**Pull request closed without merging**
