### PR TITLE
Adjust translation system

### PR DESCRIPTION
**Pull request by NathanBnm**
I added the 'value' attribute of inputs as translatable content to help translate some buttons like the 'Use Paypal' button in issue #1685

### Changes Summary

- Added `value` attribute in `L10n.php` file at line 300
- Added `"Use Paypal" : "",` at line 16 in each `get-involved.json` file
- Translated "Use Paypal" into french as "Utiliser Paypal"

**This pull request is ready for review.**

### CODE REVIEW

**Comment by NathanBnm** [comment]
@btkostner are you going to merge these changes soon ? You approved the changes but I can't merge the branch with the master branch by myself.

**Comment by btkostner** [comment]
@NathanBnm 	sorry, I think mobile was not working when I approved.

**Comment by NathanBnm** [comment]
Thanks :+1:

**Comment by NathanBnm** [comment]
Is it possible to do the same without having to change each file one by one ? There's also a title attribute which is missing.

**Pull request merged**
