### PR TITLE
add developer redirect to developer.elementary.io

### PR DESCRIPTION
**Pull request by btkostner**
Redirects developer page to `developer.elementary.io` subdomain.

We will need to update translations to remove the stale ones once this goes to master.

### CODE REVIEW

**Comment by danrabbit** [comment]
Adding "on hold" while we work out cert issues and the like

**Comment by btkostner** [comment]
This should be good to merge into master now as everything should be setup and working as intended

**Comment by danrabbit** [comment]
I opened [a small issue](https://github.com/elementary/houston/issues/314) to avoid a regression :)

**Comment by danrabbit** [comment]
I can confirm that all the metadata twitter socially stuff is working again.

**Comment by btkostner** [comment]
In the famous words of developers everywhere, "I really hope this doesn't break in production."

**Pull request merged**
