### PR TITLE
Homepage redesign & button shadows

### PR DESCRIPTION
**Pull request by jwinnie**
A miscellaneous collection of style tweaks.

Makes the AppCenter description on the homepage more like the AppCenter description on Houston; it adds highlights of purple and more bold branding.
appcenter

I am an amateur web developer, so please point it out if I made any mistakes.

This pull request IS ready for review.

### CODE REVIEW

**Comment by btkostner** [comment]
Nice! Thanks for the PR! Off the top of my head the link style will probably need to be changed for contrast, but I like the idea and adding color to the homepage. I'll pass it around to some of the UI guys and see how they like the change and get back to you.

**Comment by jwinnie** [comment]
I also made a lot of changes to the layout, text, styling, etc. of the website.

**Comment by jwinnie** [comment]
@btkostner Maybe you should use something like https://app.assignees.io/ to auto assign reviewers

**Comment by jwinnie** [comment]
Why not? Someone might drop the ball in the future, too, and I didn’t feel all that good bothering the maintainers about my PR. Plus, it’s smart, so it assigns the most relevant person

**Comment by danrabbit** [comment]
Hey @jwinnie thanks for your branch! Right now redesigning the home page is a bit low on my priority list. There are a whole lot of other people who also need me to review their branches and everyone's branch is the most important to them. I appreciate your patience!

**Comment by jwinnie** [comment]
Thanks @danrabbit! I appreciate your work and good luck!

**Comment by cassidyjames** [comment]
@jwinnie I've pulled this into #2056 since we wanted a lot more content and other changes. Thanks for providing the base on which we've built the updates!

**Pull request closed without merging**
