### PR TITLE
Updated image links in learning-the-basics in docs.

### PR DESCRIPTION
**Pull request by IamLizu**
Images in (elementary/website/blob/master/docs/learning-the-basics.md](https://github.com/elementary/website/blob/master/docs/learning-the-basics.md) are broken. Fixed imaged by updating urls.

This pull request is ready for review.

### CODE REVIEW

**Comment by peteruithoven** [comment]
The images on https://elementary.io/docs/learning-the-basics#learning-the-basics have always worked fine for me.

**Comment by IamLizu** [comment]
> The images on https://elementary.io/docs/learning-the-basics#learning-the-basics have always worked fine for me.

Yes. Does that page not served from the repository anymore? or what? Images in the markdown files don't load. But the site loads them, caching or what? Please help me understand.

**Comment by peteruithoven** [comment]
> But the site loads them, caching or what?

Because the url's only make sense in the context of the site.

**Comment by IamLizu** [comment]
Thank you!

**Pull request closed without merging**
