### PR TITLE
Allow users to download previous releases they purchased

### LINKED ISSUE #2089: Inelegant handling of Loki "download again" links
Right now if someone who purchased Loki clicks the "Download Again" link in their email, they just get dumped to the Juno page and get asked to pay again, but without any context. This comes off as something is broken, and they cannot download the previous version they already paid for. Consequently, we're receiving emails from customers who are unable to get at their download.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/64987839-inelegant-handling-of-loki-download-again-links?utm_campaign=plugin&utm_content=tracker%2F10548672&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F10548672&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by lewisgoddard**
Fixes #2089

The design remit here is to allow users who paid for a previous release to still access their product, while pointing them to the newer release as well.

### Changes Summary

- Add config for previous release
- Add page to download previous release (paid users only)

### Unchanged Summary
- Does not effect any element of the homepage
- Still redirects purchasers of the most recent major version to the homepage

---

This pull request is ready for review.
This pull request is **not** ready for merge.

### CODE REVIEW

**Comment by btkostner** [comment]
Weird question, but why not check for ANY ISO version and just show the download button like we currently do for current releases?

**Comment by cassidyjames** [comment]
@btkostner I think we don't want to miss out on users who would like to purchase the newer version as well.

**Comment by lewisgoddard** [comment]
I was expressly told that we still wanted Loki users to be able to download the latest release of Loki.

**Comment by cassidyjames** [comment]
@lewisgoddard I'm happy with the copy for now but am not sure how to test this functionally. If @btkostner or someone else can sign off on the code/functionality, let's get this merged.

**Comment by btkostner** [comment]
This will require some changes to the server config

**Comment by cassidyjames** [comment]
@btkostner what server-side changes are needed, and can we get those sorted? We're still getting a ton of emails from paying customers about this issue.

**Pull request merged**
