### PR TITLE
add webp building for images

### LINKED ISSUE #1600: Impliment webp image format
### Expected behavior

Use the latest and greated image format to improve speed. Gracefully degrade to larger images when needed. 

### Actual behavior

We use an old, dated, image formats.

### PR DESCRIPTION
**Pull request by btkostner**
Fixes #1600 

### Changes Summary

- [X] Add image build step to convert all images to webp
- [X] Add responsive build step that creates resized versions of all images
- [x] Add gulp cache for reduced build time
- [x] Add PHP function for easy creation of `picture` tags
- [x] Update all `img` tags to `picture` tags

This PR is **is** ready for review @ https://beta.elementary.io/webp/

### CODE REVIEW

**Comment by btkostner** [comment]
This is now a working branch. Two things need to happen before we merge though:

- [ ] Someone with hidpi needs to make sure all the media queries are correct and the images look good
- [ ] The homepage hero image needs to be fixed (css issue)

**Comment by btkostner** [comment]
Alright, this is updated and working as intended on my end. Time for review!

**Comment by btkostner** [comment]
Can I get @cassidyjames or @danrabbit to build this and check the images (media queries) look good on hidpi? Pretty please!

**Comment by lewisgoddard** [comment]
- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE
- [ ] Android
- [ ] iOS

**Comment by cassidyjames** [comment]
@btkostner is this worth getting back in sync with master?

**Comment by btkostner** [comment]
This is probably a pain to update. Might be better just to create a new PR. I still have yet to get `webp` images to work in `picture` elements though. At some point I'll take a closer look at image enchancements in conjunction with System76 work.

**Pull request closed without merging**
