### PR TITLE
Optimize images

### LINKED ISSUE #1471: All images should be compressed without losing quality.
### Expected behavior

Website loads swiftly upon visiting the homepage.

### Actual behavior

On both mobile and desktop, the homepage of the website takes a few seconds to fully load (on mobile ~10 seconds and ~9s on desktop).

### Steps to reproduce the behavior

1. Visit the official elementary website 
2. observe the page loading speed and start counting

### System information

- **Operating system**: Elementary OS
- **Operating system version**: Loki
- **Browser**: Firefox
- **Browser version**: 49.0.2 
- **Enabled Browser Extensions**: None

### Observations & Recommendations
I think the culprit or at least major contributor to the slow loading homepage is the notebook.png image. Using a tool like https://tinypng.com/ or https://compressor.io/ can reduce the image size quite a bit. I tried tinypng and the reduction in image size was 74% and I could see no difference in the image quality.

On a larger scale, optimizing the images on the website may improve the web pages load time.

### PR DESCRIPTION
**Pull request by btkostner**
https://beta.elementary.io/opti-ama-ze/

Fixes #1471 

### Changes Summary

- Updates build packages
- Uses babel ENV preset to only target needed browsers
- **Ran all images with pngquant**

### Stats

Tests ran from my local laptop, on chrome, with throttle set to normal 3g speed (750kb/s, 250kb/s), using the beta domain. These are not perfect, and may change a bit each time, but from the multiple tries each time was within a second difference.

Current master:
- 70 requests
- 3.6MB transfered
- Finished @ 41.65 seconds
- DOM Loaded @ 1.67 seconds
- Loaded @ 41.33 seconds

Current commit:
- 70 requests
- 1.4MB transfered
- Finished @ 17.11 seconds
- DOM loaded @ 1.35 seconds
- Loaded @ 16.94 seconds

### CODE REVIEW

**Comment by lewisgoddard** [comment]
If you compare https://raw.githubusercontent.com/elementary/website/b3028a82569768959914c796b1a8df3f980b33be/images/notebook.png and https://raw.githubusercontent.com/elementary/website/4bcec605edcdc2b86dcfdf9c6d847f3998c8af6a/images/notebook.png you'll notice the difference in the characters nose in the video player.

**Comment by btkostner** [comment]
@lewisgoddard I'm currently on a crappy 17 inch laptop with 1600x900 resolution, so I'm not able to see a whole lot of detail right now. I'll try tuning the settings a bit better when I get to my desktop. Also keep in mind, that `notebook.png` is currently 1.1MB and in this branch is 305kb.

**Comment by btkostner** [comment]
So removing the pngquant commit, and only using lossless, the changes are _very very_ underwelming.

I'll try optimizing with a less aggressive setting

**Comment by btkostner** [comment]
So, running `svgo` on all the svg files removed all the white space, creating a _really_ big PR line diff. Sorry.

Current result on beta domain: 3.6 MB down to 1.6 MB.

**Comment by lewisgoddard** [comment]
Is this pull request currently lossless?

**Comment by btkostner** [comment]
The avg changes are lossless, the screenshots to jpg are not. While we could run svgo on build, it was just increase the b #

**Comment by lewisgoddard** [comment]
Okay, but going forward how do we guarantee that SVGs don't have whitespace?

**Comment by btkostner** [comment]
I don't think we need to guarantee it, but it's something useful to do every now and then to avoid things like [svgs with inline images that do nothing](https://raw.githubusercontent.com/elementary/website/master/images/slingshot/arrow.svg).

**Comment by lewisgoddard** [comment]
Hm, I feel like it would be useful to be enforced, similar for PNG and JPG. I would like to not get this image size creep that seems to be becoming typical. We've been here before, so once we find a happy medium we should automate.

**Comment by btkostner** [comment]
Alright, I'll work on the gulp tasks for this then. I'll also move all the images to `_images` to avoid overwriting files.

**Comment by btkostner** [comment]
This should be good for review now.

**Comment by lewisgoddard** [comment]
Would I be right in thinking that this makes all the images have solid backgrounds? It seems to remove the transparency.

**Comment by btkostner** [comment]
I switched out all of the screenshots from png to jpg to save space. I kept the original png images though, in case we need to change the background color or something.

**Comment by danrabbit** [comment]
@lewisgoddard these images seem to be of the same quality to me

**Comment by btkostner** [comment]
I'll deploy this tonight when we have less people on the site.

**Pull request merged**
