### PR TITLE
fix homepage title for social previews

### LINKED ISSUE #1340: Change home page title
Maybe better to change the page title to the tagline "A fast and open replacement for Windows and OS X" since this shows up on social media previews and such

### PR DESCRIPTION
**Pull request by btkostner**
Fixes #1340

### Changes Summary

- Do not update the page title with JS
- Update page title to "A fast and open replacement for Windows and OS X"

### CODE REVIEW

**Comment by lewisgoddard** [comment]
This will break the translation on the page titles.

**Comment by btkostner** [comment]
@lewisgoddard seems to be working as intended https://beta.elementary.io/homepage-title/es/

**Comment by lewisgoddard** [comment]
Huh, I didn't think that worked for title tags.

**Comment by lewisgoddard** [comment]
I'm fairly certain it will be bad for SEO for us not to have "elementary OS" in the title tag.

**Comment by btkostner** [comment]
Worth noting that because I added the `elementary` to the title we have no translations for it

**Comment by lewisgoddard** [comment]
Should it be "elementary" or "elementary OS"?

The OS is what the description is describing.

**Comment by btkostner** [comment]
I just copied the ending we use on all the other pages:

Support: `Support &sdot; elementary`
Store: `Store &sdot; elementary`
Developer: `Developer &sdot; elementary`

**Comment by lewisgoddard** [comment]
The store, support, and developer are about things other than the OS, but the homepage is currently OS only. I feel like it might help with SEO, our rankings are a little tentative.

**Pull request merged**
