### PR TITLE
Update Font Awesome version

### LINKED ISSUE #2151: Update Slack Icon
Slack just reviewed their interface and icon as explained in this article : https://slackhq.com/say-hello-new-logo
Maybe the old icon should be replaced by the new one ?

### PR DESCRIPTION
**Pull request by NathanBnm**
Fixes #2151 

### Changes Summary

- Update Font Awesome CSS link in `header.php`

**This pull request is ready for review.**

### CODE REVIEW

**Comment by NathanBnm** [comment]
@btkostner maybe you can test it again I replaced the new integrity key with the older one.

**Comment by NathanBnm** [comment]
@btkostner if you're online, can you just check this again please?

**Comment by btkostner** [comment]
Still getting the error. We are trying to find the login info for our account so we can get the link again. Give us a bit.

**Comment by NathanBnm** [comment]
> Still getting the error. We are trying to find the login info for our account so we can get the link again. Give us a bit.

I understand :) That's because you're registred as pro so you need to get your own integrity key I mean.

**Comment by NathanBnm** [comment]
@btkostner did you find the link now?

**Comment by NathanBnm** [comment]
Last version is now 5.8.1

**Comment by lewisgoddard** [comment]
Closing in favour of #2217

**Pull request closed without merging**
