### PR TITLE
Correct typo in docs

### PR DESCRIPTION
**Pull request by seyDoggy**
The docs, under "Adding Translations", reads `make pot` but when I ran
this command it failed. I tried running with `make po` and that was
successful. I assume this is a typo.

Fixes #

### Changes Summary

- all instances of `make pot` replaced with `make po`.

This pull request [ is ] ready for review.

### CODE REVIEW

**Comment by danrabbit** [comment]
Hm no `make pot` is the correct command here. What was the error output?

**Comment by seyDoggy** [comment]
Hmm... I will go back and check tonight.

+1 (519) 574-9788
Adam Merrifield

**Comment by seyDoggy** [comment]
Here is the error output when using `make pot`:

```sh
adam@adam-T450 ~/Projects/hello-world/hello-again/build
  % make pot                                                              20:12
/usr/bin/xgettext: error while opening "/home/adam/Projects/hello-world/hello-again/po/hello-again.pot" for reading: No such file or directory
po/CMakeFiles/pot.dir/build.make:57: recipe for target 'pot' failed
make[3]: *** [pot] Error 1
CMakeFiles/Makefile2:160: recipe for target 'po/CMakeFiles/pot.dir/all' failed
make[2]: *** [po/CMakeFiles/pot.dir/all] Error 2
CMakeFiles/Makefile2:167: recipe for target 'po/CMakeFiles/pot.dir/rule' failed
make[1]: *** [po/CMakeFiles/pot.dir/rule] Error 2
Makefile:188: recipe for target 'pot' failed
make: *** [pot] Error 2
```

However `make po` works and generates a whole list of .po files:

```sh
..
├── AUTHORS
├── build
│   ├── CMakeCache.txt
│   ├── CMakeFiles
│   │   ├── 3.5.1
│   │   │   ├── CMakeCCompiler.cmake
│   │   │   ├── CMakeCXXCompiler.cmake
│   │   │   ├── CMakeDetermineCompilerABI_C.bin
│   │   │   ├── CMakeDetermineCompilerABI_CXX.bin
│   │   │   ├── CMakeSystem.cmake
│   │   │   ├── CompilerIdC
│   │   │   │   ├── a.out
│   │   │   │   └── CMakeCCompilerId.c
│   │   │   └── CompilerIdCXX
│   │   │       ├── a.out
│   │   │       └── CMakeCXXCompilerId.cpp
│   │   ├── cmake.check_cache
│   │   ├── CMakeDirectoryInformation.cmake
│   │   ├── CMakeOutput.log
│   │   ├── CMakeRuleHashes.txt
│   │   ├── CMakeTmp
│   │   ├── feature_tests.bin
│   │   ├── feature_tests.c
│   │   ├── feature_tests.cxx
│   │   ├── hello-again.dir
│   │   │   ├── build.make
│   │   │   ├── C.includecache
│   │   │   ├── cmake_clean.cmake
│   │   │   ├── DependInfo.cmake
│   │   │   ├── depend.internal
│   │   │   ├── depend.make
│   │   │   ├── flags.make
│   │   │   ├── link.txt
│   │   │   ├── progress.make
│   │   │   └── src
│   │   │       └── hello-again.c.o
│   │   ├── Makefile2
│   │   ├── Makefile.cmake
│   │   ├── progress.marks
│   │   └── TargetDirectories.txt
│   ├── cmake_install.cmake
│   ├── hello-again
│   ├── hello-again_valac.stamp
│   ├── install_manifest.txt
│   ├── Makefile
│   ├── po
│   │   ├── CMakeFiles
│   │   │   ├── CMakeDirectoryInformation.cmake
│   │   │   ├── i18n.dir
│   │   │   │   ├── build.make
│   │   │   │   ├── cmake_clean.cmake
│   │   │   │   ├── DependInfo.cmake
│   │   │   │   └── progress.make
│   │   │   ├── pot.dir
│   │   │   │   ├── build.make
│   │   │   │   ├── cmake_clean.cmake
│   │   │   │   ├── DependInfo.cmake
│   │   │   │   ├── depend.internal
│   │   │   │   ├── depend.make
│   │   │   │   └── progress.make
│   │   │   └── progress.marks
│   │   ├── cmake_install.cmake
│   │   └── Makefile
│   └── src
│       └── hello-again.c
├── CMakeLists.txt
├── CMakeLists.txt~
├── COPYING
├── data
│   └── hello.desktop
├── po
│   ├── aa.po
│   ├── ab.po
│   ├── ae.po
│   ├── af.po
│   ├── ak.po
│   ├── am.po
│   ├── an.po
│   ├── ar.po
│   ├── as.po
│   ├── ast.po
│   ├── av.po
│   ├── ay.po
│   ├── az.po
│   ├── ba.po
│   ├── be.po
│   ├── bg.po
│   ├── bh.po
│   ├── bi.po
│   ├── bm.po
│   ├── bn.po
│   ├── bo.po
│   ├── br.po
│   ├── bs.po
│   ├── ca.po
│   ├── ce.po
│   ├── ch.po
│   ├── ckb.po
│   ├── CMakeLists.txt
│   ├── CMakeLists.txt~
│   ├── co.po
│   ├── cr.po
│   ├── cs.po
│   ├── cu.po
│   ├── cv.po
│   ├── cy.po
│   ├── da.po
│   ├── de.po
│   ├── dv.po
│   ├── dz.po
│   ├── ee.po
│   ├── el.po
│   ├── en_AU.po
│   ├── en_CA.po
│   ├── en_GB.po
│   ├── eo.po
│   ├── es.po
│   ├── et.po
│   ├── eu.po
│   ├── fa.po
│   ├── ff.po
│   ├── fi.po
│   ├── fj.po
│   ├── fo.po
│   ├── fr_CA.po
│   ├── fr.po
│   ├── fy.po
│   ├── ga.po
│   ├── gd.po
│   ├── gl.po
│   ├── gn.po
│   ├── gu.po
│   ├── gv.po
│   ├── ha.po
│   ├── he.po
│   ├── hi.po
│   ├── ho.po
│   ├── hr.po
│   ├── ht.po
│   ├── hu.po
│   ├── hy.po
│   ├── hz.po
│   ├── ia.po
│   ├── id.po
│   ├── ie.po
│   ├── ig.po
│   ├── ii.po
│   ├── ik.po
│   ├── io.po
│   ├── is.po
│   ├── it.po
│   ├── iu.po
│   ├── ja.po
│   ├── jv.po
│   ├── ka.po
│   ├── kg.po
│   ├── ki.po
│   ├── kj.po
│   ├── kk.po
│   ├── kl.po
│   ├── km.po
│   ├── kn.po
│   ├── ko.po
│   ├── kr.po
│   ├── ks.po
│   ├── ku.po
│   ├── kv.po
│   ├── kw.po
│   ├── ky.po
│   ├── la.po
│   ├── lb.po
│   ├── lg.po
│   ├── li.po
│   ├── ln.po
│   ├── lo.po
│   ├── lt.po
│   ├── lu.po
│   ├── lv.po
│   ├── mg.po
│   ├── mh.po
│   ├── mi.po
│   ├── mk.po
│   ├── ml.po
│   ├── mn.po
│   ├── mo.po
│   ├── mr.po
│   ├── ms.po
│   ├── mt.po
│   ├── my.po
│   ├── na.po
│   ├── nb.po
│   ├── nd.po
│   ├── ne.po
│   ├── ng.po
│   ├── nl.po
│   ├── nn.po
│   ├── no.po
│   ├── nr.po
│   ├── nv.po
│   ├── ny.po
│   ├── oc.po
│   ├── oj.po
│   ├── om.po
│   ├── or.po
│   ├── os.po
│   ├── pa.po
│   ├── pi.po
│   ├── pl.po
│   ├── ps.po
│   ├── pt_BR.po
│   ├── pt.po
│   ├── qu.po
│   ├── rm.po
│   ├── rn.po
│   ├── ro.po
│   ├── rue.po
│   ├── ru.po
│   ├── rw.po
│   ├── sa.po
│   ├── sc.po
│   ├── sd.po
│   ├── se.po
│   ├── sg.po
│   ├── si.po
│   ├── sk.po
│   ├── sl.po
│   ├── sma.po
│   ├── sm.po
│   ├── sn.po
│   ├── so.po
│   ├── sq.po
│   ├── sr.po
│   ├── ss.po
│   ├── st.po
│   ├── su.po
│   ├── sv.po
│   ├── sw.po
│   ├── ta.po
│   ├── te.po
│   ├── tg.po
│   ├── th.po
│   ├── ti.po
│   ├── tk.po
│   ├── tl.po
│   ├── tn.po
│   ├── to.po
│   ├── tr.po
│   ├── ts.po
│   ├── tt.po
│   ├── tw.po
│   ├── ty.po
│   ├── ug.po
│   ├── uk.po
│   ├── ur.po
│   ├── uz.po
│   ├── ve.po
│   ├── vi.po
│   ├── vo.po
│   ├── wa.po
│   ├── wo.po
│   ├── xh.po
│   ├── yi.po
│   ├── yo.po
│   ├── za.po
│   ├── zh_CN.po
│   ├── zh_HK.po
│   ├── zh.po
│   ├── zh_TW.po
│   └── zu.po
└── src
    ├── hello-again
    ├── hello-again.c
    └── hello-again.vala

16 directories, 257 files
```

**Comment by luizaugustomm** [comment]
I've found another typo in the [replace](https://elementary.io/docs/code/getting-started#replace) section.

There's a variable called `replace_button`, but right in the next line that is referenced as `update_button`. When I changed the later name to the former the code was compiled successfully.

**Comment by lewisgoddard** [comment]
I'm going to close this as it seems it was more likely an issue generating language files on a certain system, and not something we had documented incorrectly.

**Pull request closed without merging**
