### PR TITLE
add payment class for common stripe functions

### LINKED ISSUE #1530: There are duplicated Stripe functions.
The functions `doStripeCheckout` and `stripeLanguage` in [`_scripts/pages/store/download.js`](https://github.com/elementary/website/blob/master/_scripts/pages/store/download.js) have near duplicates in [`_scripts/pages/store/checkout.js`](https://github.com/elementary/website/blob/master/_scripts/pages/store/checkout.js).

### PR DESCRIPTION
**Pull request by btkostner**
Fixes #1530

### Changes Summary

- Moves the common Stripe payment code to a new `Payment` class that handles language determination and key setting. All wrapped up in a nice promise.

### CODE REVIEW

**Comment by lewisgoddard** [comment]
Can we set https://beta.elementary.io/payment-class/ for Stripe testing? It doesn't seem to work there currently. That or this just needs fixing.

**Comment by btkostner** [comment]
Alright, that was weird. The compressing of scripts was causing a runtime error, but only on the server (not locally). Anyway, it's fixed now and ready to be reviewed. I would still avoid merging it for a bit until Dan says it's ok.

**Comment by lewisgoddard** [comment]
@danrabbit Apparently we're waiting on you saying this is okay?

**Comment by lewisgoddard** [comment]
dan said it was okay.

**Pull request merged**
