### PR TITLE
OS X on the name change of the current

### PR DESCRIPTION
**Pull request by igor-dyatlov**
- [x] Homepage
- [ ] `/docs/installation`

### CODE REVIEW

**Comment by cassidyjames** [comment]
This sounds good to me now that macOS has a release date, though I'm not sure if we want to wait for that date or switch now.

**Comment by danrabbit** [comment]
Apple has macOS on their website now. I'm okay with whatever

**Comment by lewisgoddard** [comment]
I guess they can retrospectively apply macOS to older versions, but the first true macOS release comes out on the 20th of September.

**Comment by cassidyjames** [comment]
I'm good with merging. @igor-dyatlov can you update this from master and then we can get it merged?

**Comment by png2378** [comment]
Please, don't break translations before the release :worried:

**Comment by lewisgoddard** [comment]
Yeah, I'd prefer to block this from `master` for a couple of weeks. It's really not a major change.

**Comment by lewisgoddard** [comment]
Also, this needs to be updated in some of the docs, notably installation.

**Comment by lewisgoddard** [comment]
Closed in favour of #1348

**Pull request closed without merging**
