### PR TITLE
Refresh for Odin

### LINKED ISSUE #2784: Update for Odin
Obviously

### PR DESCRIPTION
**Pull request by cassidyjames**
Fixes #2784 and updates the site for OS 6:

- Refreshes the tagline
- Replaces Hera info with Odin in What's New and on Press page
- Bumps the example config (will need actual config update for launch)
- Updates screenshots; standardizes on single HiDPI screenshots with explicit sizes for crispness on loDPI
- Fixes workflow section styling for new screenshot dimensions
- Updates app showcase styling for new wallpaper
- Reworks Parental Controls section for Screen Time & Limits
- Replaces Location Services in Privacy section with Permissions
- Updates and expands the Privacy page with more info for Odin
- "Pay what you want" → "Pay what you can" as we've previously discussed
- Replaces interactive JS Terminal with static screenshot like all other apps
- Adds installation video embed to docs
- Updates installation docs to standardize on Etcher

While I was here:
- Removes the outdated purple nav for the docs style since remaining docs are user-facing
- Standardizes on 2-space tabs for any files I touched (we use 2-space tabs on other web projects and were mixing 2-space, 4-space, and tab characters here)
- Updates the Privacy page style to match the homepage section
- Removes the "Pantheon" styles and scripts since they're unused now

Protip: the diff number is scary; view hiding whitespace changes.

### CODE REVIEW

**Comment by danrabbit** [comment]
I guess this needs to remove the toast now :)

**Comment by danrabbit** [comment]
something has gone awry!

Screenshot from 2021-08-04 16 29 04

**Comment by danrabbit** [comment]
There's a screenshot of switchboard on the OEM page that needs to be updated:

Screenshot from 2021-08-04 16 30 53

**Comment by danrabbit** [comment]
New privacy page design is FIRE

I noticed that on the "Open Source" page we link to POA on launchpad as well as Ubiquity and LibUnity, which can all be dropped. And GTK+ is just GTK now right?

I guess we should drop BountySource from the OpenSource page while we're here and didn't we sponsor like LAS or GUADEC or something?

The screenshots on the "Learning the basics" page are outdated

**Comment by cassidyjames** [comment]
@danrabbit the toast is behind a timer so it will automatically be gone once this is deployed anyway. But I can explicitly re-remove it. :shrug:

**Comment by cassidyjames** [comment]
@danrabbit addressed everything you raised.

**Comment by danrabbit** [comment]
Shortcuts screenshot is double size in LoDPI, but it's now the right aspect ratio!

Tattle-tale, Permissions, and Housekeeping icons are all blurry. It looks like there's a `transform: scale(1.25)` on `#privacy h4 svg`

Everything else looks great! Nice work

**Review by danrabbit — DISMISSED** [review]
Looks good! Been over it a couple times and everything is great. Nice work and nice diff!

**Pull request merged**
