### PR TITLE
Use PSR-2 coding standard, add PHP_CodeSniffer. Resolves #1657

### LINKED ISSUE #1657: Startin linting PHP files
### Expected behavior

Nice clean PHP code style.

### Actual behavior

Tabs with spaces and spaces with tabs.

### The solution

We add [CodeSniffer](https://github.com/squizlabs/PHP_CodeSniffer) with the PSR2 standard to the list of CI tests.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/44186208-add-phpcs-to-lint-php-files?utm_campaign=plugin&utm_content=tracker%2F10548672&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F10548672&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by carstendietrich**
Hello,

had some free time. Changed the indent and refactored stuff to match PSR-2. Furthermore I added PHPCS as a Composer dependency. Refactoring is in separate commits for easier review. I also moved Parsedown and ParsedownExtra to Composer for easier updates. PHPCS only shows some minor warnings.

After `composer install` please run PHP_CodeSniffer in the project root to review the warnings:
`./_backend/vendor/squizlabs/php_codesniffer/bin/phpcs --standard=PSR2 --ignore=*/vendor/* --extensions=php .`

### Changes Summary

Resolves issue #1657.

- Add PHPCS as Composer dependency
- Use PHPCBF to get rid of all indent related errors / warnings
- Refactor classes to use camel case method names (`\Store\Address\Address`, `\App\Lib\L10n`)
- Add missing namespace to class `\ValidationException`
- Move `Parsedown` and `ParsedownExtra` to Composer, remove obsolete require and settings.

### After Merge

- [ ] Add PHPCS check to TravisCI

- [ ] Update contributor guide (general usage of PHPCS and maybe a pre commit hook to ensure proper code style)

**This pull request is ready for review.**

### CODE REVIEW

**Comment by btkostner** [comment]
This is a lot for a PR, but it had to happen at some point. I'll take a look at it when I get a chance, but it will probably be a while. Thanks for taking the time to do this.

**Comment by carstendietrich** [comment]
Jeah I really thought about just refactoring small parts of the code like updating dependencies or reducing the complexity of several classes. But I guess we should first do some basic tasks like code style and use current tooling during CI. Afterwards contributing should offer a better experience and diffs should be smaller.

Parts of the code are quite old and probably hard to maintain, continuing with the current workflow will lead to more and more legacy code. This should be avoided unless there are plans for a complete relaunch of the website.

**Comment by btkostner** [comment]
Also, random question: Any reason you used `PHP_CodeSniffer` instead of [`PHP-CS-Fixer`](https://github.com/FriendsOfPHP/PHP-CS-Fixer)?

**Comment by carstendietrich** [comment]
Hi,

I'm currently on vacation, so sorry for the delayed answer. I'll be home in 1-2 days, then I will diff the ParsedownExtra from the repo with the one provided by composer and merge the changes from master.

PHP_CodeSniffer and PHP-CS-Fixer follow different approaches, the CodeSniffer concentrates on the linting of the code, whereby the CS-Fixer aims at solving code style problems. Both projects offer an additional fixer/linter and are actively maintained. So it is more a question of personal preferences and the problem that should be solved. In our case, I chose CodeSniffer to actively remind developers to use a specific code style, not just to automatically correct it. I also worked on other projects with CodeSniffer and had good experience using it in combination with a pre commit hook and general developer acceptance.

I guess this choice is up for discussion.

**Pull request closed without merging**
