### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by btkostner**
This adds a `Dockerfile` that will build and host the website.

This moves the actual PHP running from `nginx` to `apache` mainly because there is no _official_ php nginx image, and I would rather just use `apache` instead of making our own. Easier to update. Easier to run. etc. etc.

Things to do:
- [ ] Port nginx config to `.htaccess`
- [ ] Setup configuration to load from environment variables
- [ ] Test
- [ ] Deploy GitHub action to publish the image to DockerHub

### CODE REVIEW

**Comment by StylusEater** [comment]
@btkostner is this still in progress?

**Comment by btkostner** [comment]
I have not touched this since the initial commit, so it's pretty stale

**Comment by StylusEater** [comment]
@btkostner Thank you for confirming.

**Comment by davidmhewitt** [comment]
Superseded by #3160

**Pull request closed without merging**
