### PR TITLE
Changed all buttons colors of get-involved page using your respective…

### LINKED ISSUE #1654: Use elementary color palette for Get Involved page
Buttons and such still use the solarized color palette, we should use our own.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/44174741-use-elementary-color-palette-for-get-involved-page?utm_campaign=plugin&utm_content=tracker%2F10548672&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F10548672&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by brunocamarggo**
Fixes #1654 

### Changes Summary

- Changed all buttons colors of get-involved page using your respective color in elementary's palette color.

This pull request is ready for review.

### CODE REVIEW

**Comment by brunocamarggo** [comment]
This is a new pull request because I delete my forked repository by mistake. Sorry guys.

**Comment by brunocamarggo** [comment]
I'll do this... Thanks for your the reply =D

**Comment by btkostner** [comment]
The banana still doesn't have a great contrast. @brunocamarggo You should try going with the #d48e15 color from [the color palette](http://danielfore.com/palette).

https://beta.elementary.io/view-1744/get-involved

**Comment by btkostner** [comment]
After some discussion, we are going to work on expanding our color palette a bit and come back to this PR.

**Comment by danrabbit** [comment]
Closing this PR since there's been no movement on it in the last month

**Pull request closed without merging**
