### PR TITLE
Rewrite the Website

### PR DESCRIPTION
**Pull request by ConnorVG**
Fixes Everything

### Changes Summary

- Stage one: remove shit
- Stage two: add grammy worthy code
- Stage three: ????
- Stage four: PROFIT

### CODE REVIEW

**Comment by JustSteveKing** [comment]
`cd /path/to/website/ && rm -rf * && composer install anything/but-this-repo . && apt-get profit`

**Comment by btkostner** [comment]
I'm going to assume this as a troll PR and close it

**Comment by Dylan-DPC** [comment]
This isn't a troll PR. Someone is taking effort in following standards that are widely practiced. So if you want to remain as an "ancient tree" feel free to but you are missing on the "cool features" and exposing to weaknesses of using ancient techniques. If you want to stay ancient, Fortran seems a better alternative

**Comment by Riari** [comment]
The website looks fantastic. It really does. But the source leaves a lot to be desired. :/

image

**Comment by btkostner** [comment]
My bad. I'm on mobile so it didn't show all the changes.

**Comment by danrabbit** [comment]
It's absolutely a troll PR. These guys are freaking morons.

**Comment by Dylan-DPC** [comment]
Ye we are moronic enough to use `find` to lilnt a PHP file... oh wait that isn't us... :speak_no_evil:

**Comment by ConnorVG** [comment]
I'm more than happy to go for this @danrabbit; though my point stands. The current implementation of the site is extremely poor. That should be held as an honest observation. I've built a lot of great websites, I'm more than happy to provide you with some examples.

But hey, if you don't want a free service then that's your choice.

**Comment by danrabbit** [comment]
@ConnorVG I've reported your account for being so helpful. Go troll some other repo

**Pull request closed without merging**
