### PR TITLE
Redesign Get Involved Design section

### PR DESCRIPTION
**Pull request by danrabbit**
My copy is bad. Halp

screenshot from 2017-04-26 18 25 36

### CODE REVIEW

**Comment by cassidyjames** [comment]
Idk something like
> elementary OS uses a system stylesheet written in CSS. It defines how everything on the screen, from buttons and toolbars to the panel and menus are drawn.

**Comment by danrabbit** [comment]
screenshot from 2017-04-27 09 22 18

Much better

**Comment by lewisgoddard** [comment]
is it just me or are those icons no longer center aligned?

**Comment by cassidyjames** [comment]
Design and copy look good. Looks like the beta server is struggling to build though.

**Comment by lewisgoddard** [comment]
Yeah, https://beta.elementary.io/get-involved-design/get-involved doesn't look good.

**Comment by Bat41** [comment]
I would like to translate in French the text you added, but it looks like they are not available on Weblate. Did you forget to make them translatable or is it me who don't know how to use Weblate? :grin:

**Comment by lewisgoddard** [comment]
Erm, @btkostner ? How often does weblate pull in new translatable strings>

**Comment by btkostner** [comment]
Weblate should pull in new translations every time you push. It just does not run the translation update script yet. There are a couple of things I need to look at to ensure it's working correctly still, but I'll try to update them soon.

**Pull request merged**
